### ISSUE TITLE
Fully migrate old roadmap

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/team-compass#6]
The goal is to close all issues from the "old" roadmap project here: https://github.com/orgs/aiidateam/projects/3 and move them here, closing eventually that project board.
Not all items from there should be moved, in some cases those should just become issues

High:

- [x] Refactoring out RabbitMQ (@sphuber todo)
- [x] maximum recursion depth reached" when submitting ~200 workchains [GP: should this just be a highly-important issue? Probably not needed to be in the roadmap. Or better: we shoudl have a general roadmap item on "robustness", as this is an important item, and this should just be a linked issue] (https://github.com/aiidateam/aiida-core/issues/4876) (remove from roadmap)
- [x] General overview of AiiDA capabilities on the docs @giovannipizzi 
- [x] General improvements to usability
- [x] Template computer/code setup and new code registry configs (#4)
- [x] Subproject - Improve profile backups [@ramirezfranciscof] (#11)
- [x] push/pull @chrisjsewell 

Mid:

- [X] Clever caching policy involving RemoteData @unkcpz (#13)
- [x] Testing framework for workflows
- [X] Rethink the distribution between what is set during computer setup (immutable) and computer configure [@ramirezfranciscof] (#12)
- [x] `ContainerizedCode`: Add support for running codes within Docker containers @sphuber #9  
- [x] Domain-agnostic AiiDA core (domain-specific materials-science plugins) (dependent on data migration for plugins) (@mbercx)
- [x] Migration of data nodes for plugins (@mbercx)
- [x] REST-API workflow management (dependent on serialization/deserialization)
- [x] Investigate how to ensure easy "re-running" of a calculation sequence that is stored in the AiiDA provenance graph @sphuber #9 
- [x] `verdi computer delete` should allow user to delete computers with associated nodes  [GP: issue rather than roadmap?]

Low (@chrisjsewell)

- [x] Hierarchical graph visualization [GP: issue rather than roadmap?] (@eimrek)
- [x] Make the optimade structure first-class citizen that can import/export to AiiDA @unkcpz (#15)
- [x] Cross-computer Scheduling
- [x] Two-factor identification @giovannipizzi 
- [x] Support Python-based codes (@sphuber) (#19)
- [x] Hide data when exporting, keep only the metadata (e.g. the fact there is a node) (@sphuber) (#18)
- [x] CLI generation for ORM classes (merge discussion with REST API generation of data classes)
- [x] REST-API plugin (early one, GraphQL) - discuss first serialization/deserialization
- [x] CLI for repository browse [GP: issue rather than roadmap?] (@giovannipizzi)
- [x] Standardised serialisation/deserialisation of data nodes  [GP: to be framed as a user-story, now it's a technical task for an issue] (@sphuber) (#17)
- [x] Create query builder from natural language @unkcpz

**Comment by sphuber** [comment]
I will convert the following items to separate issues:
* Investigate how to ensure easy "re-running" of a calculation sequence that is stored in the AiiDA provenance graph
* ContainerizedCode: Add support for running codes within Docker containers


Also the following entries are really the same I think:
* REST-API workflow management (dependent on serialization/deserialization)
* REST-API plugin (early one, GraphQL) - discuss first serialization/deserialization

**Comment by ramirezfranciscof** [comment]
I can do the migration for:
- Subproject - Improve profile backups
- Rethink the distribution between what is set during computer setup (immutable) and computer configure

Note: probably also won't have much time today, but try to do it tomorrow or early next week.

**Comment by unkcpz** [comment]
I'll do the migration for:

- Make the optimade structure first-class citizen that can import/export to AiiDA
- Create query builder from natural language
- Clever caching policy involving RemoteData

Maybe also convert already the AEP in the [discussion for new docker aiida image](https://github.com/aiidateam/aiida-core/discussions/5714)

Note: don't have time this week, but will do it next week.
