### ISSUE TITLE
Usability: Provide general overview of the AiiDA ecosystem on the docs

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/team-compass#8]
## Motivation
The AiiDA ecosystem has grown over time. Beside aiida-core, a lot of functionality very relevant to users (especially from Materials Science and similar fields) is actually implemented not in the core, but in a number of side packages/plugins that are also maintained by the core AIiDA team.
In addition, some features (e.g. how to setup AiiDA to run at scale for high-throughput, or design suggestions on how to organise the work in such cases) are known to a number of core developers and explained orally, but are not written down in a location that is easy to find (the [tuning performance](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/installation.html#tuning-performance) section of the docs goes in this direction, but I found it only because I knew it existed, and I had to guess in which section it was).
If users do not find easily this information, they might not be aware of existing implementation (e.g. robust Quantum ESPRESSO workflows), or might not configure AiiDA appropriately and incorrectly assume that AiiDA is not performant enough for their throughput. 

## Desired Outcome

The main AiiDA documentation should have, already in the homepage, a clear section focused on highlighting more general usecases and linking to which AiiDA components (core, plugins, ...) can help solve that issue. 
This should be very easy to find (a couple of clicks to reach, intuitively findable by a person who wants to know how to use AiiDA for high-throughput materials science, ...) - we should use some colleagues to check if any practical solution to this roadmap item is really easy to find.

For each main topic we want to address (see list below), ideally a user who has installed AiiDA should have clear "bullet-point" instructions and steps to start using that feature in, say, < 10 minutes. 

## Impact

We ensure that users find easily the large amount of code, plugins, workflows that we have developed and can immediately benefit of AiiDA. This indirectly gives a strong motivation to users to make the effort to overcome the initial learning barrier of AiiDA, as they can immediately profit from a number of advanced features (robust workflows, high-throughput capabilities ,...).

## Complexity

The complexity is relatively low, and this requires essentially zero coding.
The complex part is ensuring that the information we add to the docs is concise enough but still contains relevant pointers so interested users can follow up and read more, and that it's really easy to be found.
I think that 2 people working on this for a few focused days (e.g. in a "coding week") can address this.

## Background
Here a list of topics that should be probably covered:
- `aiida-quantumespresso` main features (not only code plugins, but most importantly advanced workflows)
- other well-supported plugins (I would consider those in the ACWF as well supported - probably also discuss ACWF itself)
- `aiida-pseudo` and how to use it
- aiida-hyperqueue and other meta-schedulers for multiple calculations inside the same job (for task farming, see #2)
- aiida-submission-controller (for limiting submission rate and managing real high-throughput jobs), and anything else needed to configure AiiDA for real HT jobs
- support of running in AiiDA containers by AiiDA
- 2FA/MFA support in AiiDA
- GUIs for AiiDA (AiiDAlab, Materials Cloud Explore, and anything else we support as a team)

## Progress
Tasks to solve this:

- [ ] dev meeting to list which features we want to cover, and update list above
- [ ] discussion on where to put these docs so that they are effective
- [ ] write up content
- [ ] check with 3-4 users if the material is findable (and clear): e.g. ask "please check in the docs how you could do task X" and see if they find it (and if not, why and improve the organisation of the new material)
- [ ] decide which of the points above is important to highlight directly in a tutorial, open issues on the tutorial docs, and implement them

**Comment by GeigerJ2** [comment]
Just to link here that we added an overview of non-research domain-specific `core` plugins to the docs [here](https://aiida.readthedocs.io/projects/aiida-core/en/latest/reference/core_plugins.html) (content to be discussed), as well as a blog post [here](https://www.aiida.net/news/posts/2024-12-13-core-plugins.html). With the use cases, #23, we probably cover many points outlined here.
